### ISSUE TITLE
Eagle files out of date with current design

### ISSUE THREAD

**Issue by jeraymond** [adafruit/Adafruit-PCF8523-RTC-Breakout-PCB#1]
Hello,

From the [image of the schematic on the Adafruit PCF8523 Real Time Clock page](https://learn.adafruit.com/adafruit-pcf8523-real-time-clock?view=all#schematic) it looks like this board has undergone a revision. There is the addition of a 10uF capacitor and 1k resistor on the VDD pin of the PCF8523 and the VCC bypass capacitor changed from 0.1 uF to 10uF. It'd be great to have the updated Eagle files pushed to Github.

![changes_schem](https://user-images.githubusercontent.com/158470/39676849-1a4b9274-5126-11e8-83cc-dc66922a61f9.png)

The published schematics are such a great learning tool. Thanks a lot for providing them.

**Comment by ladyada** [comment]
k!

**Comment by jeraymond** [comment]
Thanks! Out of curiosity, what problem did adding the 1k resistor and capacitor to the VDD pin solve?

**Comment by ladyada** [comment]
unexpected power droops causing time loss
